# Generated by Django 4.0.6 on 2022-09-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0003_remove_comment_user_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_main.teacher')),
            ],
        ),
    ]
